### ISSUE TITLE
Docker Compose ?

### ISSUE THREAD

**Issue by accforgithubtest** [xitanggg/open-resume#14]
Would be great to have this containerized, and be self-hosted via docker.

**Comment by xitanggg** [comment]
#19 is merged thanks to @mahalel and @inveracity 's great work. You should be able to start a docker container by following the below test steps if you pull the latest change:
1. Download the repo `git clone https://github.com/xitanggg/open-resume.git`
2. Change the directory `cd open-resume`
3. Build the container `docker build -t open-resume .`
4. Start the container `docker run -p 3000:3000 open-resume`
5. Open your browser and visit [http://localhost:3000](http://localhost:3000) to see OpenResume live

Marking this as closed now

**Comment by accforgithubtest** [comment]
Any chances of having an image hosted on dockerhub ? It would be useful for folks looking to pull an image and not having to clone the repo locally.
