### ISSUE TITLE
I love your product, request to use your code

### ISSUE THREAD

**Issue by sergioUjo** [xitanggg/open-resume#21]
Hi am creating a tailor cv app, and I love you features. I want to add them to my [website](https://www.tailoredcv.app/); we could also join forces if you fancy that.
Is it ok for me to peak into your code to develop mine? 
Would you like to join forces?

**Comment by xitanggg** [comment]
Thank you for your kind words and love! OpenResume is an open-source app and is licensed under [GPLv3](https://github.com/xitanggg/open-resume/blob/main/LICENSE). This gist might be helpful you might not be familiar with GPLv3: https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60
