### ISSUE TITLE
[feature request] add chinese language support for builder?

### ISSUE THREAD

**Issue by dabuside** [xitanggg/open-resume#28]

**Comment by xitanggg** [comment]
Hi there, thanks for creating this issue. React PDF would only display the font correctly if the corresponding font family is registered for it to use. Previously, Chinese font wasn't added and registered, hence the PDF output was garbled code.

I just merged #40 and this PR adds the `思源黑体 (简体)` font. If user has `zh` language in their browser's `navigator.languages` property, user would see `思源黑体 (简体)` listed as one of the font option in the font family section 
https://user-images.githubusercontent.com/23644661/257455861-174687a1-808c-4e74-8c86-23819c949ab3.gif

![Recording 2023-08-01 at 1 35 27 AM](https://github.com/xitanggg/open-resume/assets/23644661/174687a1-808c-4e74-8c86-23819c949ab3)

More context can be found in this thread: https://github.com/xitanggg/open-resume/issues/36#issuecomment-1659840384
