### ISSUE TITLE
Just wanted to appreciate the effort!

### ISSUE THREAD

**Issue by AmruthPillai** [xitanggg/open-resume#72]
Hey there!

I maintain another similar open-source project (https://github.com/AmruthPillai/Reactive-Resume), also a resume builder, so I could really appreciate the work you've put into this project. There's a lot I could learn from this as well, especially with how you parse resumes, that's quite the engineering feat. I'd love to pick your brain on it some time.

Kudos for the project, hope you have fewer issues and more stars soon!

**Comment by xitanggg** [comment]
👋 Hi @AmruthPillai , thank you so much for your kind words and for stopping by. Your project [Reactive-Resume](https://github.com/AmruthPillai/Reactive-Resume) has been a huge inspiration to me and OpenResume with its many amazing features❤️ OpenResume is a simpler alternative with a narrower set of features that tailor to the US market 🙌
