### ISSUE TITLE
Add a save option [Feature]

### ISSUE THREAD

**Issue by jeanpaulh** [xitanggg/open-resume#79]
I have to say thanks; it is looking great.
I shared an issue about the PDF file that you generated isn't being passed correctly when you import it.
Being a PDF, I would think this would be hard; maybe a better option is to add a save option [MetaData]!!!!

keep up the good work.

JP

**Comment by tracker1** [comment]
Dupe of #62

**Comment by jeanpaulh** [comment]
dupe
