### ISSUE TITLE
Create a Docker Container for deployment

### ISSUE THREAD

**Issue by HStep20** [xitanggg/open-resume#8]
Looks really neat, but without a dockerfile, its unlikely that a lot of people will deploy it locally. It'd be great to have a container + Registry/tag set up here on github for future releases to autobuild and release for end users.

**Comment by xitanggg** [comment]
Thanks for the kind word. Great feedback on dockizing it to make it easier to deploy. The app is currently deployed with Vercel since it integrates nicely with Nextjs. It can be run locally with `npm install` then `npm run dev`, but agree that dockizing it would make it easier to deploy
